global: 
  scrape_interval: 5s

scrape_configs: 
  - job_name: "prometheus"
    static_configs: 
      - targets: ["localhost:9090"]

  - job_name: "node_proc"
    static_configs: 
      - targets: ["node_proc:5000"]
